<?php

use App\Http\Controllers\Admin\AnnouncementController as AdminAnnouncementController;
use App\Http\Controllers\Admin\ActivityController;
use App\Http\Controllers\Admin\BackupController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\GalleryController as AdminGalleryController;
use App\Http\Controllers\Admin\MissionController as AdminMissionController;
use App\Http\Controllers\Admin\GuideController as AdminGuideController;
use App\Http\Controllers\Admin\LotteryController;
use App\Http\Controllers\Admin\MediaController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\OutingController as AdminOutingController;
use App\Http\Controllers\Admin\RankingController as AdminRankingController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\StuffController as AdminStuffController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ValidationController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MissionController;
use App\Http\Controllers\GuideController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OutingController;
use App\Http\Controllers\RankingController;
use App\Http\Controllers\StuffController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('accueil');
Route::redirect('/accueil', '/', 301);

Route::get('/classement', [RankingController::class, 'index'])->name('classement');
Route::get('/galerie', [GalleryController::class, 'index'])->name('galerie');
Route::get('/guides', [GuideController::class, 'index'])->name('guides.index');
Route::get('/guides/{guide:slug}', [GuideController::class, 'show'])->name('guides.show');
Route::get('/missions', [MissionController::class, 'index'])->name('missions.index');
Route::middleware('auth')->group(function (): void {
    Route::get('/profil', [ProfileController::class, 'show'])->name('profil');
    Route::patch('/profil', [ProfileController::class, 'update'])->name('profil.update');
    Route::post('/profil/avatar', [ProfileController::class, 'updateAvatar'])->name('profil.avatar.update');
    Route::patch('/profil/mot-de-passe', [ProfileController::class, 'updatePassword'])->name('profil.password.update');
    Route::post('/profil/missions', [ProfileController::class, 'storeMissionValidation'])->name('profil.missions.store');
    Route::delete('/profil', [ProfileController::class, 'destroy'])->name('profil.destroy');
});
Route::get('/sorties', [OutingController::class, 'index'])->name('sorties.index');
Route::get('/stuffs', [StuffController::class, 'index'])->name('stuffs.index');
Route::redirect('/login', '/connexion')->name('login');
Route::middleware('guest')->group(function (): void {
    Route::get('/connexion', [AuthenticatedSessionController::class, 'create'])->name('connexion');
    Route::post('/connexion', [AuthenticatedSessionController::class, 'store'])->name('connexion.store');
    Route::get('/inscription', [AuthenticatedSessionController::class, 'register'])->name('inscription');
    Route::post('/inscription', [AuthenticatedSessionController::class, 'signup'])->name('inscription.store');
    Route::get('/mot-de-passe-oublie', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/mot-de-passe-oublie', [PasswordResetLinkController::class, 'store'])->name('password.email');
    Route::get('/mot-de-passe/reinitialiser/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/mot-de-passe/reinitialiser', [NewPasswordController::class, 'store'])->name('password.store');
});

Route::post('/deconnexion', [AuthenticatedSessionController::class, 'destroy'])
    ->middleware('auth')
    ->name('deconnexion');

Route::middleware('auth')->group(function (): void {
    Route::post('/sorties/{outing}/vote', [OutingController::class, 'vote'])->name('sorties.vote');
    Route::delete('/sorties/{outing}/vote', [OutingController::class, 'cancel'])->name('sorties.vote.cancel');
});

Route::middleware(['auth', 'admin'])->group(function (): void {
    Route::get('/admin', DashboardController::class)->name('admin.dashboard');
    Route::delete('/admin/activite', [ActivityController::class, 'destroy'])->middleware('admin:activity')->name('admin.activite.destroy');
    Route::get('/admin/activite/{area?}', [ActivityController::class, 'index'])->middleware('admin:activity')->name('admin.activite.index');
    Route::get('/admin/mediatheque/images', [MediaController::class, 'picker'])->name('admin.mediatheque.images');
    Route::get('/admin/mediatheque', [MediaController::class, 'index'])->middleware('admin:media')->name('admin.mediatheque.index');
    Route::delete('/admin/mediatheque', [MediaController::class, 'destroy'])->middleware('admin:media')->name('admin.mediatheque.destroy');
    Route::get('/admin/notifications', [NotificationController::class, 'index'])->middleware('admin:notifications')->name('admin.notifications.index');
    Route::patch('/admin/notifications/lues', [NotificationController::class, 'markAllRead'])->middleware('admin:notifications')->name('admin.notifications.read-all');
    Route::delete('/admin/notifications', [NotificationController::class, 'destroy'])->middleware('admin:notifications')->name('admin.notifications.destroy');
    Route::get('/admin/annonces', [AdminAnnouncementController::class, 'index'])->middleware('admin:announcements')->name('admin.annonces.index');
    Route::get('/admin/annonces/creer', [AdminAnnouncementController::class, 'create'])->middleware('admin:announcements')->name('admin.annonces.create');
    Route::post('/admin/annonces', [AdminAnnouncementController::class, 'store'])->middleware('admin:announcements')->name('admin.annonces.store');
    Route::get('/admin/annonces/corbeille', [AdminAnnouncementController::class, 'trash'])->middleware('admin:announcements')->name('admin.annonces.trash');
    Route::delete('/admin/annonces/corbeille', [AdminAnnouncementController::class, 'emptyTrash'])->middleware('admin:announcements,delete')->name('admin.annonces.empty-trash');
    Route::patch('/admin/annonces/corbeille/{announcement}/restaurer', [AdminAnnouncementController::class, 'restore'])->middleware('admin:announcements')->name('admin.annonces.restore');
    Route::delete('/admin/annonces/corbeille/{announcement}', [AdminAnnouncementController::class, 'forceDelete'])->middleware('admin:announcements,delete')->name('admin.annonces.force-delete');
    Route::get('/admin/annonces/{announcement}/modifier', [AdminAnnouncementController::class, 'edit'])->middleware('admin:announcements')->name('admin.annonces.edit');
    Route::patch('/admin/annonces/{announcement}', [AdminAnnouncementController::class, 'update'])->middleware('admin:announcements')->name('admin.annonces.update');
    Route::delete('/admin/annonces/{announcement}', [AdminAnnouncementController::class, 'destroy'])->middleware('admin:announcements,delete')->name('admin.annonces.destroy');
    Route::view('/admin/commentaires', 'admin.admin-comments')->middleware('admin:comments')->name('admin.commentaires.index');
    Route::get('/admin/galerie', [AdminGalleryController::class, 'index'])->middleware('admin:gallery')->name('admin.galerie.index');
    Route::get('/admin/galerie/creer', [AdminGalleryController::class, 'create'])->middleware('admin:gallery')->name('admin.galerie.create');
    Route::post('/admin/galerie', [AdminGalleryController::class, 'store'])->middleware('admin:gallery')->name('admin.galerie.store');
    Route::get('/admin/galerie/corbeille', [AdminGalleryController::class, 'trash'])->middleware('admin:gallery')->name('admin.galerie.trash');
    Route::delete('/admin/galerie/corbeille', [AdminGalleryController::class, 'emptyTrash'])->middleware('admin:gallery,delete')->name('admin.galerie.empty-trash');
    Route::patch('/admin/galerie/corbeille/{image}/restaurer', [AdminGalleryController::class, 'restore'])->middleware('admin:gallery')->name('admin.galerie.restore');
    Route::delete('/admin/galerie/corbeille/{image}', [AdminGalleryController::class, 'forceDelete'])->middleware('admin:gallery,delete')->name('admin.galerie.force-delete');
    Route::get('/admin/galerie/{image}/modifier', [AdminGalleryController::class, 'edit'])->middleware('admin:gallery')->name('admin.galerie.edit');
    Route::patch('/admin/galerie/{image}', [AdminGalleryController::class, 'update'])->middleware('admin:gallery')->name('admin.galerie.update');
    Route::delete('/admin/galerie/{image}', [AdminGalleryController::class, 'destroy'])->middleware('admin:gallery,delete')->name('admin.galerie.destroy');
    Route::get('/admin/guides', [AdminGuideController::class, 'index'])->middleware('admin:guides')->name('admin.guides.index');
    Route::get('/admin/guides/creer', [AdminGuideController::class, 'create'])->middleware('admin:guides')->name('admin.guides.create');
    Route::post('/admin/guides', [AdminGuideController::class, 'store'])->middleware('admin:guides')->name('admin.guides.store');
    Route::get('/admin/guides/corbeille', [AdminGuideController::class, 'trash'])->middleware('admin:guides')->name('admin.guides.trash');
    Route::delete('/admin/guides/corbeille', [AdminGuideController::class, 'emptyTrash'])->middleware('admin:guides,delete')->name('admin.guides.empty-trash');
    Route::patch('/admin/guides/corbeille/{guide}/restaurer', [AdminGuideController::class, 'restore'])->middleware('admin:guides')->name('admin.guides.restore');
    Route::delete('/admin/guides/corbeille/{guide}', [AdminGuideController::class, 'forceDelete'])->middleware('admin:guides,delete')->name('admin.guides.force-delete');
    Route::get('/admin/guides/{guide}/modifier', [AdminGuideController::class, 'edit'])->middleware('admin:guides')->name('admin.guides.edit');
    Route::patch('/admin/guides/{guide}', [AdminGuideController::class, 'update'])->middleware('admin:guides')->name('admin.guides.update');
    Route::delete('/admin/guides/{guide}', [AdminGuideController::class, 'destroy'])->middleware('admin:guides,delete')->name('admin.guides.destroy');
    Route::get('/admin/loterie', [LotteryController::class, 'index'])->middleware('admin:lottery')->name('admin.loterie.index');
    Route::get('/admin/missions', [AdminMissionController::class, 'index'])->middleware('admin:missions')->name('admin.missions.index');
    Route::get('/admin/missions/creer', [AdminMissionController::class, 'create'])->middleware('admin:missions')->name('admin.missions.create');
    Route::post('/admin/missions', [AdminMissionController::class, 'store'])->middleware('admin:missions')->name('admin.missions.store');
    Route::get('/admin/missions/corbeille', [AdminMissionController::class, 'trash'])->middleware('admin:missions')->name('admin.missions.trash');
    Route::delete('/admin/missions/corbeille', [AdminMissionController::class, 'emptyTrash'])->middleware('admin:missions,delete')->name('admin.missions.empty-trash');
    Route::patch('/admin/missions/corbeille/{mission}/restaurer', [AdminMissionController::class, 'restore'])->middleware('admin:missions')->name('admin.missions.restore');
    Route::delete('/admin/missions/corbeille/{mission}', [AdminMissionController::class, 'forceDelete'])->middleware('admin:missions,delete')->name('admin.missions.force-delete');
    Route::get('/admin/missions/{mission}/modifier', [AdminMissionController::class, 'edit'])->middleware('admin:missions')->name('admin.missions.edit');
    Route::patch('/admin/missions/{mission}', [AdminMissionController::class, 'update'])->middleware('admin:missions')->name('admin.missions.update');
    Route::delete('/admin/missions/{mission}', [AdminMissionController::class, 'destroy'])->middleware('admin:missions,delete')->name('admin.missions.destroy');
    Route::get('/admin/classement', [AdminRankingController::class, 'index'])->middleware('admin:ranking')->name('admin.classement.index');
    Route::get('/admin/roles', [RoleController::class, 'index'])->middleware('admin:roles')->name('admin.roles.index');
    Route::get('/admin/roles/creer', [RoleController::class, 'create'])->middleware('admin:roles')->name('admin.roles.create');
    Route::post('/admin/roles', [RoleController::class, 'store'])->middleware('admin:roles')->name('admin.roles.store');
    Route::get('/admin/roles/corbeille', [RoleController::class, 'trash'])->middleware('admin:roles')->name('admin.roles.trash');
    Route::delete('/admin/roles/corbeille', [RoleController::class, 'emptyTrash'])->middleware('admin:roles,delete')->name('admin.roles.empty-trash');
    Route::patch('/admin/roles/corbeille/{role}/restaurer', [RoleController::class, 'restore'])->middleware('admin:roles')->name('admin.roles.restore');
    Route::delete('/admin/roles/corbeille/{role}', [RoleController::class, 'forceDelete'])->middleware('admin:roles,delete')->name('admin.roles.force-delete');
    Route::get('/admin/roles/{role}/modifier', [RoleController::class, 'edit'])->middleware('admin:roles')->name('admin.roles.edit');
    Route::patch('/admin/roles/{role}', [RoleController::class, 'update'])->middleware('admin:roles')->name('admin.roles.update');
    Route::delete('/admin/roles/{role}', [RoleController::class, 'destroy'])->middleware('admin:roles,delete')->name('admin.roles.destroy');
    Route::get('/admin/parametres', [SettingController::class, 'index'])->middleware('admin:settings')->name('admin.parametres.index');
    Route::patch('/admin/parametres/cycle', [SettingController::class, 'updateCycle'])->middleware('admin:settings,cycle')->name('admin.parametres.cycle.update');
    Route::patch('/admin/parametres/points', [SettingController::class, 'updatePoints'])->middleware('admin:settings,points')->name('admin.parametres.points.update');
    Route::patch('/admin/parametres/loterie', [SettingController::class, 'updateLottery'])->middleware('admin:settings,lottery')->name('admin.parametres.lottery.update');
    Route::patch('/admin/parametres/maintenance', [SettingController::class, 'updateMaintenance'])->middleware('admin:settings,maintenance')->name('admin.parametres.maintenance.update');
    Route::post('/admin/parametres/sauvegardes', [BackupController::class, 'store'])->middleware('admin:settings,backups')->name('admin.parametres.backups.store');
    Route::get('/admin/parametres/sauvegardes/{backup}', [BackupController::class, 'download'])->middleware('admin:settings,backups')->name('admin.parametres.backups.download');
    Route::post('/admin/parametres/sauvegardes/{backup}/restaurer', [BackupController::class, 'restore'])->middleware('admin:settings,backups')->name('admin.parametres.backups.restore');
    Route::delete('/admin/parametres/sauvegardes/{backup}', [BackupController::class, 'destroy'])->middleware('admin:settings,backups')->name('admin.parametres.backups.destroy');
    Route::get('/admin/sorties', [AdminOutingController::class, 'index'])->middleware('admin:outings')->name('admin.sorties.index');
    Route::get('/admin/sorties/creer', [AdminOutingController::class, 'create'])->middleware('admin:outings')->name('admin.sorties.create');
    Route::post('/admin/sorties', [AdminOutingController::class, 'store'])->middleware('admin:outings')->name('admin.sorties.store');
    Route::get('/admin/sorties/corbeille', [AdminOutingController::class, 'trash'])->middleware('admin:outings')->name('admin.sorties.trash');
    Route::delete('/admin/sorties/corbeille', [AdminOutingController::class, 'emptyTrash'])->middleware('admin:outings,delete')->name('admin.sorties.empty-trash');
    Route::patch('/admin/sorties/corbeille/{outing}/restaurer', [AdminOutingController::class, 'restore'])->middleware('admin:outings')->name('admin.sorties.restore');
    Route::delete('/admin/sorties/corbeille/{outing}', [AdminOutingController::class, 'forceDelete'])->middleware('admin:outings,delete')->name('admin.sorties.force-delete');
    Route::get('/admin/sorties/{outing}/modifier', [AdminOutingController::class, 'edit'])->middleware('admin:outings')->name('admin.sorties.edit');
    Route::patch('/admin/sorties/{outing}/valider', [AdminOutingController::class, 'confirm'])->middleware('admin:outings')->name('admin.sorties.confirm');
    Route::patch('/admin/sorties/{outing}', [AdminOutingController::class, 'update'])->middleware('admin:outings')->name('admin.sorties.update');
    Route::delete('/admin/sorties/{outing}', [AdminOutingController::class, 'destroy'])->middleware('admin:outings,delete')->name('admin.sorties.destroy');
    Route::get('/admin/stuffs', [AdminStuffController::class, 'index'])->middleware('admin:stuffs')->name('admin.stuffs.index');
    Route::get('/admin/stuffs/creer', [AdminStuffController::class, 'create'])->middleware('admin:stuffs')->name('admin.stuffs.create');
    Route::post('/admin/stuffs', [AdminStuffController::class, 'store'])->middleware('admin:stuffs')->name('admin.stuffs.store');
    Route::get('/admin/stuffs/corbeille', [AdminStuffController::class, 'trash'])->middleware('admin:stuffs')->name('admin.stuffs.trash');
    Route::delete('/admin/stuffs/corbeille', [AdminStuffController::class, 'emptyTrash'])->middleware('admin:stuffs,delete')->name('admin.stuffs.empty-trash');
    Route::patch('/admin/stuffs/corbeille/{stuff}/restaurer', [AdminStuffController::class, 'restore'])->middleware('admin:stuffs')->name('admin.stuffs.restore');
    Route::delete('/admin/stuffs/corbeille/{stuff}', [AdminStuffController::class, 'forceDelete'])->middleware('admin:stuffs,delete')->name('admin.stuffs.force-delete');
    Route::get('/admin/stuffs/{stuff}/modifier', [AdminStuffController::class, 'edit'])->middleware('admin:stuffs')->name('admin.stuffs.edit');
    Route::patch('/admin/stuffs/{stuff}', [AdminStuffController::class, 'update'])->middleware('admin:stuffs')->name('admin.stuffs.update');
    Route::delete('/admin/stuffs/{stuff}', [AdminStuffController::class, 'destroy'])->middleware('admin:stuffs,delete')->name('admin.stuffs.destroy');
    Route::get('/admin/utilisateurs', [UserController::class, 'index'])->middleware('admin:users')->name('admin.utilisateurs.index');
    Route::get('/admin/utilisateurs/creer', [UserController::class, 'create'])->middleware('admin:users')->name('admin.utilisateurs.create');
    Route::post('/admin/utilisateurs', [UserController::class, 'store'])->middleware('admin:users')->name('admin.utilisateurs.store');
    Route::get('/admin/utilisateurs/corbeille', [UserController::class, 'trash'])->middleware('admin:users')->name('admin.utilisateurs.trash');
    Route::delete('/admin/utilisateurs/corbeille', [UserController::class, 'emptyTrash'])->middleware('admin:users,delete')->name('admin.utilisateurs.empty-trash');
    Route::patch('/admin/utilisateurs/corbeille/{user}/restaurer', [UserController::class, 'restore'])->middleware('admin:users')->name('admin.utilisateurs.restore');
    Route::delete('/admin/utilisateurs/corbeille/{user}', [UserController::class, 'forceDelete'])->middleware('admin:users,delete')->name('admin.utilisateurs.force-delete');
    Route::get('/admin/utilisateurs/{user}/modifier', [UserController::class, 'edit'])->middleware('admin:users')->name('admin.utilisateurs.edit');
    Route::patch('/admin/utilisateurs/{user}/valider', [UserController::class, 'approve'])->middleware('admin:users')->name('admin.utilisateurs.approve');
    Route::patch('/admin/utilisateurs/{user}', [UserController::class, 'update'])->middleware('admin:users')->name('admin.utilisateurs.update');
    Route::delete('/admin/utilisateurs/{user}', [UserController::class, 'destroy'])->middleware('admin:users,delete')->name('admin.utilisateurs.destroy');
    Route::get('/admin/validations', [ValidationController::class, 'index'])->middleware('admin:validations')->name('admin.validations.index');
    Route::get('/admin/validations/creer', [ValidationController::class, 'create'])->middleware('admin:validations')->name('admin.validations.create');
    Route::post('/admin/validations', [ValidationController::class, 'store'])->middleware('admin:validations')->name('admin.validations.store');
    Route::get('/admin/validations/corbeille', [ValidationController::class, 'trash'])->middleware('admin:validations')->name('admin.validations.trash');
    Route::delete('/admin/validations/corbeille', [ValidationController::class, 'emptyTrash'])->middleware('admin:validations,delete')->name('admin.validations.empty-trash');
    Route::patch('/admin/validations/corbeille/{validation}/restaurer', [ValidationController::class, 'restore'])->middleware('admin:validations')->name('admin.validations.restore');
    Route::delete('/admin/validations/corbeille/{validation}', [ValidationController::class, 'forceDelete'])->middleware('admin:validations,delete')->name('admin.validations.force-delete');
    Route::get('/admin/validations/{validation}/modifier', [ValidationController::class, 'edit'])->middleware('admin:validations')->name('admin.validations.edit');
    Route::patch('/admin/validations/{validation}', [ValidationController::class, 'update'])->middleware('admin:validations')->name('admin.validations.update');
    Route::patch('/admin/validations/{validation}/statut', [ValidationController::class, 'setStatus'])->middleware('admin:validations')->name('admin.validations.status');
    Route::delete('/admin/validations/{validation}', [ValidationController::class, 'destroy'])->middleware('admin:validations,delete')->name('admin.validations.destroy');
});
