<?php

return [
    'lengths' => [
        'easy' => 4,
        'normal' => 5,
        'hard' => 6,
    ],

    'rewards' => [
        'easy' => [
            1 => 12000,
            2 => 11000,
            3 => 10000,
            4 => 9000,
            5 => 8000,
            6 => 7000,
        ],
        'normal' => [
            1 => 30000,
            2 => 28000,
            3 => 25000,
            4 => 22000,
            5 => 20000,
            6 => 18000,
        ],
        'hard' => [
            1 => 60000,
            2 => 55000,
            3 => 50000,
            4 => 45000,
            5 => 40000,
            6 => 35000,
        ],
    ],

    'bank' => [
        'easy' => [
            ['word' => 'Zaap', 'hint' => 'Point de passage que les aventuriers utilisent pour voyager vite.'],
            ['word' => 'Piou', 'hint' => 'Petit oiseau colore que l on croise tres tot.'],
            ['word' => 'Ocre', 'hint' => 'Couleur d un Dofus lie a une grande chasse.'],
            ['word' => 'Pods', 'hint' => 'Quand ils manquent, l inventaire devient un probleme.'],
            ['word' => 'Koli', 'hint' => 'Format de combat ou trois joueurs cherchent la victoire.'],
            ['word' => 'Mule', 'hint' => 'Personnage secondaire souvent la pour aider le principal.'],
            ['word' => 'Drop', 'hint' => 'Ce qu on espere voir tomber a la fin du combat.'],
            ['word' => 'Craft', 'hint' => 'Il transforme les ressources en objet utile.'],
            ['word' => 'Mine', 'hint' => 'Lieu sombre ou les minerais attirent les travailleurs.'],
            ['word' => 'Bois', 'hint' => 'Ressource que le bucheron connait bien.'],
            ['word' => 'Pain', 'hint' => 'Apres un combat, il remet souvent sur pied.'],
            ['word' => 'Bouf', 'hint' => 'Debut d une famille laineuse tres connue.'],
            ['word' => 'Mage', 'hint' => 'Il aime modifier les jets des equipements.'],
            ['word' => 'Cape', 'hint' => 'Piece d equipement portee dans le dos.'],
            ['word' => 'Amak', 'hint' => 'Raccourci pour penser au vieux continent des aventuriers.'],
            ['word' => 'Abraknyde', 'hint' => 'Il a des racines, mais il ne reste pas toujours immobile.'],
            ['word' => 'Bwork', 'hint' => 'On le reconnait souvent avant meme de comprendre ce qu il dit.'],
            ['word' => 'Chacha', 'hint' => 'Compagnon a moustaches, parfois plus fier qu utile.'],
            ['word' => 'Gelano', 'hint' => 'Petit anneau, grand souvenir pour beaucoup de joueurs.'],
            ['word' => 'Kanigrou', 'hint' => 'Il saute rarement dans la bonne direction pour toi.'],
            ['word' => 'Prespic', 'hint' => 'Sa defense donne envie de compter ses coups.'],
            ['word' => 'Sanglier', 'hint' => 'Il charge, pousse, et ruine parfois un placement propre.'],
            ['word' => 'Scara', 'hint' => 'Une couleur suffit souvent a changer ce qu on cherche sur lui.'],
            ['word' => 'Wabbit', 'hint' => 'Son accent est presque aussi connu que ses oreilles.'],
            ['word' => 'Dragoeuf', 'hint' => 'Quand la coquille bouge, ce n est pas toujours rassurant.'],
            ['word' => 'Minotoror', 'hint' => 'Il garde un labyrinthe ou beaucoup se sont deja perdus.'],
            ['word' => 'Blop', 'hint' => 'Il a une couleur, une famille, et une facheuse tendance a coller.'],
            ['word' => 'Corbac', 'hint' => 'On l associe plus volontiers aux plumes sombres qu aux bonnes nouvelles.'],
            ['word' => 'Pichon', 'hint' => 'Petit habitant aquatique souvent croise par les debutants.'],
            ['word' => 'Larve', 'hint' => 'Avant d etre impressionnant, il faut parfois ramper.'],
            ['word' => 'Arakne', 'hint' => 'Elle aime les coins, les fils, et les joueurs distraits.'],
            ['word' => 'Pissenlit', 'hint' => 'Il a l air fragile, jusqu au moment ou il attaque.'],
            ['word' => 'Tournesol', 'hint' => 'Une fleur qui a appris a rendre les coups.'],
            ['word' => 'Moskitto', 'hint' => 'Petit, bruyant, et rarement invite dans les combats tranquilles.'],
            ['word' => 'Chafer', 'hint' => 'Il continue de se battre alors qu il lui manque deja beaucoup.'],
            ['word' => 'Cochon', 'hint' => 'Dans certaines plaines, il vaut mieux se mefier des groins.'],
            ['word' => 'Boos', 'hint' => 'Son nom est court, mais il peut vite remplir une zone.'],
            ['word' => 'Milimulou', 'hint' => 'Une version moins imposante, mais pas forcement moins penible.'],
            ['word' => 'Tronknyde', 'hint' => 'On dirait qu un morceau de foret a pris une decision.'],
            ['word' => 'Forgeron', 'hint' => 'Quand il travaille, le metal n est jamais tres loin.'],
            ['word' => 'Boulanger', 'hint' => 'Son metier peut sauver plus de pauses qu un sort de soin.'],
            ['word' => 'Alchimiste', 'hint' => 'Entre fioles et plantes, il prepare souvent l utile.'],
            ['word' => 'Mineur', 'hint' => 'Il cherche la valeur la ou beaucoup ne voient que de la roche.'],
            ['word' => 'Bucheron', 'hint' => 'Il transforme les forets en ressources tres demandees.'],
            ['word' => 'Pecheur', 'hint' => 'Il sait attendre longtemps pour remplir son inventaire.'],
            ['word' => 'Cawotte', 'hint' => 'Un legume orange devenu bien plus celebre qu il ne devrait.'],
            ['word' => 'Doplon', 'hint' => 'Petite monnaie gagnee a force de defis repetes.'],
            ['word' => 'Percepteur', 'hint' => 'Il recolte pendant que d autres prennent les risques.'],
            ['word' => 'Havresac', 'hint' => 'Un petit chez-soi que l on transporte partout.'],
        ],
        'normal' => [
            ['word' => 'Dofus', 'hint' => 'Oeuf legendaire que beaucoup cherchent a reunir.'],
            ['word' => 'Kamas', 'hint' => 'La monnaie qui decide souvent du prochain achat.'],
            ['word' => 'Xelor', 'hint' => 'Classe qui aime jouer avec le temps et les PA.'],
            ['word' => 'Sacri', 'hint' => 'Classe qui transforme la douleur en puissance.'],
            ['word' => 'Enips', 'hint' => 'Raccourci pour les soigneurs aux mots precieux.'],
            ['word' => 'Roubl', 'hint' => 'Raccourci d une classe qui adore les bombes.'],
            ['word' => 'Hupper', 'hint' => 'Classe liee aux elements et aux runes.'],
            ['word' => 'Ougin', 'hint' => 'Classe canine qui piste sa proie sans douceur.'],
            ['word' => 'Tengu', 'hint' => 'Gardien glace souvent accompagne dans son combat.'],
            ['word' => 'Klime', 'hint' => 'Un mauvais placement rend vite son combat penible.'],
            ['word' => 'Ougah', 'hint' => 'Quand les champignons deviennent une vraie menace.'],
            ['word' => 'Scara', 'hint' => 'Une famille coloree que les debutants connaissent bien.'],
            ['word' => 'Larve', 'hint' => 'Avant de devenir impressionnant, il faut parfois ramper.'],
            ['word' => 'Arbre', 'hint' => 'Dans ce monde, il peut parfois rendre les coups.'],
            ['word' => 'Perco', 'hint' => 'Il recolte pour une guilde pendant que les autres combattent.'],
            ['word' => 'Dinde', 'hint' => 'Monture coloree qui accompagne beaucoup d aventuriers.'],
            ['word' => 'Prism', 'hint' => 'Objet de conquete lie aux alliances.'],
            ['word' => 'Runee', 'hint' => 'Elle sert a tenter de modifier un equipement.'],
            ['word' => 'Glyphe', 'hint' => 'Zone posee au sol qui peut punir les pas.'],
            ['word' => 'Idole', 'hint' => 'Ancien defi qui compliquait les combats contre recompense.'],
            ['word' => 'Aerdala', 'hint' => 'Le vent y a plus d importance que la pierre.'],
            ['word' => 'Akwadala', 'hint' => 'Une ile, un element, et beaucoup d humidite dans l air.'],
            ['word' => 'Feudala', 'hint' => 'Ici, la chaleur ne vient pas seulement du decor.'],
            ['word' => 'Terrdala', 'hint' => 'Le sol y semble plus bavard que le ciel.'],
            ['word' => 'Nimbos', 'hint' => 'Un peuple de montagne qui ne manque pas d altitude.'],
            ['word' => 'Koalak', 'hint' => 'Derriere son air rond, la zone peut vite devenir penible.'],
            ['word' => 'Kanniboul', 'hint' => 'Sur son ile, mieux vaut ne pas finir au menu.'],
            ['word' => 'Bworker', 'hint' => 'Il n a pas besoin de parler proprement pour faire mal.'],
            ['word' => 'Ratblanc', 'hint' => 'Un souverain des egouts qui n aime pas les visiteurs propres.'],
            ['word' => 'Ratnoir', 'hint' => 'Son royaume souterrain sent rarement la victoire facile.'],
            ['word' => 'Skeunk', 'hint' => 'Son repaire a laisse des souvenirs a plus d un groupe.'],
            ['word' => 'Meulou', 'hint' => 'Une fourrure celebre, souvent liee a de vieux objectifs de stuff.'],
            ['word' => 'Mansot', 'hint' => 'Il vient du froid, mais ses combats rechauffent vite l equipe.'],
            ['word' => 'Royalmouth', 'hint' => 'Un monarque glacial avec un nom qui mache fort.'],
            ['word' => 'Mulous', 'hint' => 'Quand la nuit et les crocs se melangent, on pense a eux.'],
            ['word' => 'Dreggon', 'hint' => 'Il evoque les dragons sans toujours en avoir la majestueuse patience.'],
            ['word' => 'Peki', 'hint' => 'Petit nom, grande capacite a agacer une equipe.'],
            ['word' => 'Craqueleur', 'hint' => 'Il donne l impression qu une montagne a decide de bouger.'],
            ['word' => 'Pandikaze', 'hint' => 'Il porte bien son nom quand il arrive trop pres.'],
            ['word' => 'Bitouf', 'hint' => 'On le croise sur une ile ou la nature adore compliquer les choses.'],
            ['word' => 'Kilibriss', 'hint' => 'Un nom qui sonne leger, mais qui ne promet pas un combat simple.'],
            ['word' => 'Poolay', 'hint' => 'Une creature qui rappelle que l ile tropicale a son humour.'],
            ['word' => 'Mufafah', 'hint' => 'Dans la savane, certains rugissements annoncent une mauvaise idee.'],
            ['word' => 'Fauchalak', 'hint' => 'Son nom donne deja envie de verifier ses points de vie.'],
            ['word' => 'Pandule', 'hint' => 'Quand le temps et l ile se croisent, on tombe sur lui.'],
            ['word' => 'Zoth', 'hint' => 'Un peuple perche qui ne se laisse pas approcher sans repondre.'],
            ['word' => 'Roissingue', 'hint' => 'Il aime les zones humides et les combats moins propres qu on voudrait.'],
            ['word' => 'Ouassingue', 'hint' => 'Son nom sent la vase, et ce n est pas un hasard.'],
            ['word' => 'Boufette', 'hint' => 'Elle appartient a une famille tres connue des aventuriers.'],
            ['word' => 'Kitsou', 'hint' => 'Quatre couleurs, une famille, et souvent des ressources recherchees.'],
            ['word' => 'Brigandin', 'hint' => 'Quand un transport devient risque, il n est parfois pas loin.'],
            ['word' => 'Dopeul', 'hint' => 'Il ressemble a une classe, mais n en a pas toujours la politesse.'],
            ['word' => 'Maitrefoux', 'hint' => 'Son nom annonce deja une certaine maitrise du feu.'],
            ['word' => 'Gourlo', 'hint' => 'Entre tonneaux et maladresse, son combat reste memorable.'],
            ['word' => 'Benripate', 'hint' => 'Un pirate qui laisse rarement repartir les visiteurs les mains propres.'],
            ['word' => 'Phorreur', 'hint' => 'Il creuse, surgit, et complique souvent les plans trop propres.'],
        ],
        'hard' => [
            ['word' => 'Nileza', 'hint' => 'Ses experiences finissent souvent sur les mauvaises cases.'],
            ['word' => 'Missiz', 'hint' => 'Elegante, froide, et peu patiente avec les erreurs.'],
            ['word' => 'Vortex', 'hint' => 'Quand le temps se plie, les tours deviennent moins confortables.'],
            ['word' => 'Bethel', 'hint' => 'Un combat ou la foi ne suffit pas toujours.'],
            ['word' => 'Guerre', 'hint' => 'Cavalier dont l arrivee n annonce rien de calme.'],
            ['word' => 'Misere', 'hint' => 'Son nom resume deja l ambiance du combat.'],
            ['word' => 'Solar', 'hint' => 'La lumiere peut aveugler autant qu elle guide.'],
            ['word' => 'Roubal', 'hint' => 'Son univers fait penser aux bombes et aux plans tordus.'],
            ['word' => 'Dragos', 'hint' => 'Famille ecailleuse souvent liee aux oeufs et aux dangers.'],
            ['word' => 'Dopeul', 'hint' => 'Il ressemble a une classe sans toujours en avoir la politesse.'],
            ['word' => 'Gelano', 'hint' => 'Petit anneau, grand souvenir pour beaucoup de joueurs.'],
            ['word' => 'Meulou', 'hint' => 'Fourrure celebre liee a de vieux objectifs de stuff.'],
            ['word' => 'Mansot', 'hint' => 'Creature venue du froid et rarement tendre.'],
            ['word' => 'Mulous', 'hint' => 'Quand la nuit et les crocs se melangent, on pense a eux.'],
            ['word' => 'Bitouf', 'hint' => 'Creature d ile tropicale qui complique vite les choses.'],
            ['word' => 'Poolay', 'hint' => 'Creature qui rappelle que l ile a son humour.'],
            ['word' => 'Kitsou', 'hint' => 'Famille coloree avec des ressources recherchees.'],
            ['word' => 'Gourlo', 'hint' => 'Entre tonneaux et maladresse, son combat reste connu.'],
            ['word' => 'Pekiou', 'hint' => 'Petit nom transforme pour rappeler un adversaire agile.'],
            ['word' => 'Nimbos', 'hint' => 'Peuple de montagne qui ne manque pas d altitude.'],
            ['word' => 'Kralamoure', 'hint' => 'Quand il ouvre la danse, toute l equipe doit connaitre ses pas.'],
            ['word' => 'Korriandre', 'hint' => 'Ici, marcher au mauvais endroit peut devenir une tres mauvaise habitude.'],
            ['word' => 'Glourseleste', 'hint' => 'Un nom doux pour un combat qui ne pardonne pas les approximations.'],
            ['word' => 'Kolossos', 'hint' => 'Il rappelle que le froid peut aussi frapper tres lourd.'],
            ['word' => 'Obsidiantre', 'hint' => 'La chaleur et la pierre y font rarement bon menage.'],
            ['word' => 'Tengu', 'hint' => 'Seul ou accompagne, il a marque une generation de joueurs givres.'],
            ['word' => 'Nileza', 'hint' => 'Ses experiences ont tendance a finir sur les mauvaises cases.'],
            ['word' => 'Sylargh', 'hint' => 'Avec lui, les jouets ne sont pas faits pour les enfants.'],
            ['word' => 'Klime', 'hint' => 'Un mauvais placement peut suffire a transformer le combat en punition.'],
            ['word' => 'Missiz', 'hint' => 'Elegante, froide, et rarement patiente avec les erreurs.'],
            ['word' => 'Merkator', 'hint' => 'La mecanique et les profondeurs y avancent main dans la main.'],
            ['word' => 'Vortex', 'hint' => 'Quand le temps se plie, les tours deviennent moins confortables.'],
            ['word' => 'Nidas', 'hint' => 'Son amour des richesses coute souvent plus cher que prevu.'],
            ['word' => 'Dantinea', 'hint' => 'Dans son domaine, respirer n est pas le seul probleme.'],
            ['word' => 'Meno', 'hint' => 'Un nom court pour une menace venue des abysses.'],
            ['word' => 'TalKasha', 'hint' => 'Les os, les maledictions et les erreurs s y accumulent vite.'],
            ['word' => 'Bethel', 'hint' => 'Un combat ou la foi ne suffit pas toujours a survivre.'],
            ['word' => 'Solar', 'hint' => 'La lumiere peut aveugler autant qu elle guide.'],
            ['word' => 'Ilyzaelle', 'hint' => 'Elle inspire autant le respect que les longues preparations.'],
            ['word' => 'Guerre', 'hint' => 'L un des cavaliers qui ne vient jamais annoncer une bonne nouvelle.'],
            ['word' => 'Servitude', 'hint' => 'Un cavalier dont le nom resume deja une partie du probleme.'],
            ['word' => 'Misere', 'hint' => 'Quand elle arrive, le combat porte bien son nom.'],
            ['word' => 'Torkelonia', 'hint' => 'Une carapace et des mecaniques qui punissent l impatience.'],
            ['word' => 'Belladone', 'hint' => 'Son nom est joli, mais il vaut mieux ne pas y gouter.'],
            ['word' => 'Protozorreur', 'hint' => 'Un laboratoire n est jamais rassurant quand lui s y trouve.'],
            ['word' => 'ReineVoleurs', 'hint' => 'Dans son domaine, les bombes ne sont pas seulement decoratives.'],
            ['word' => 'Chaloeil', 'hint' => 'Un regard suffit parfois a comprendre que le placement compte.'],
            ['word' => 'ComteHarebourg', 'hint' => 'Son nom est lie au froid, au temps et aux longues strategies.'],
            ['word' => 'Ush', 'hint' => 'Un nom tres court pour un adversaire qui aime les jeux dangereux.'],
            ['word' => 'Bworker', 'hint' => 'Sa brutalite a marque des joueurs bien avant les combats modernes.'],
            ['word' => 'Ougah', 'hint' => 'Quand les champignons deviennent une menace serieuse.'],
            ['word' => 'SphincterCell', 'hint' => 'Un nom impossible a oublier apres etre passe dans ses egouts.'],
            ['word' => 'Rasboul', 'hint' => 'Il a longtemps teste la patience et le placement des equipes.'],
            ['word' => 'Minotot', 'hint' => 'Dans le meme labyrinthe, il fait monter le niveau d un cran.'],
        ],
    ],
];
